-- ════════════════════════════════════════════════════════════════════
-- peakplant — subscribers (ONE list: waitlist + monthly newsletter)
--
-- DOKUMENTATION DES LIVE-ZUSTANDS (verifiziert 14.08.2026) — NICHT AUSFÜHREN.
-- Die frühere Version dieser Datei beschrieb Spalten (`status`, `locale`) und
-- eine Tabelle (`newsletter_sends`), die live NIE existiert haben; genau diese
-- Abweichung ließ jede Anmeldung auf der Live-Site mit PostgREST 400
-- fehlschlagen, bis der Code auf die echten Spalten umgestellt wurde.
-- `subscribers` ist eine geschützte Tabelle (MANIFESTO §4): Migrationen
-- rühren sie nicht an. Änderungen an Policies laufen als nummerierte
-- Migration (siehe 0015_drift_repair.sql), nie über diese Datei.
-- ════════════════════════════════════════════════════════════════════

-- Live-Schema (real existierende Spalten):
--
--   create table public.subscribers (
--     id          uuid primary key default gen_random_uuid(),
--     email       text not null unique,   -- unique → doppelte Anmeldung = 409
--     source      text,                   -- "homepage-de", "community-en", …
--                                         -- die SPRACHE reist im Suffix mit,
--                                         -- es gibt KEINE locale-Spalte
--     edition     text,                   -- "edition_01"
--     created_at  timestamptz not null default now()
--   );
--
-- RLS: aktiviert. Policies nach 0015:
--   * SELECT nur service_role ("allow_service_select")
--   * KEIN anon-INSERT mehr (0015 entfernt "allow_anon_insert" — Inserts
--     laufen ausschließlich server-seitig über /api/waitlist mit
--     service_role, validiert und rate-limitiert)
--
-- Abmelden = DELETE der Zeile (es gibt keine status-Spalte; nichts bleibt
-- zurück, an das man schreiben könnte). Der Monatsbrief liest email+source
-- mit service_role und leitet die Sprache aus dem source-Suffix ab.
--
-- `newsletter_sends` existiert nicht — der Code-Pfad, der hineinschreiben
-- wollte, wurde am 13.08. entfernt (Entscheidung in 0015 dokumentiert).
