import { Edition, Memory, MomentCard, Space, SpaceMember, User } from './types';

export const SEED_USER: User = {
  id: 'user-01',
  name: 'Alicia',
};

/**
 * The current user belongs to two spaces: a couple space and a friends space.
 * This demonstrates multi-space membership — the same model, different type.
 */
export const SEED_SPACES: Space[] = [
  {
    id: 'space-couple-01',
    type: 'couple',
    name: 'Alicia & Partner',
    inviteCode: 'PEAK-7842',
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'space-friends-01',
    type: 'friends',
    name: 'The Saturday People',
    inviteCode: 'PEAK-3310',
    createdAt: '2026-04-02T18:00:00Z',
  },
];

export const SEED_MEMBERS: SpaceMember[] = [
  { id: 'm-1', spaceId: 'space-couple-01', userId: 'user-01', name: 'Alicia', role: 'owner', joinedAt: '2026-03-15T10:00:00Z' },
  { id: 'm-2', spaceId: 'space-couple-01', userId: 'user-02', name: 'Partner', role: 'member', joinedAt: '2026-03-15T11:00:00Z' },
  { id: 'm-3', spaceId: 'space-friends-01', userId: 'user-01', name: 'Alicia', role: 'member', joinedAt: '2026-04-02T18:00:00Z' },
  { id: 'm-4', spaceId: 'space-friends-01', userId: 'user-03', name: 'Jonas', role: 'owner', joinedAt: '2026-04-02T18:00:00Z' },
  { id: 'm-5', spaceId: 'space-friends-01', userId: 'user-04', name: 'Mira', role: 'member', joinedAt: '2026-04-02T18:05:00Z' },
];

/**
 * Edition 01 — Grow Together (20 cards)
 * Structure: 5 Grow Dates · 5 Small Acts of Growth · 10 Growing Questions
 *
 * Physical card: EN short prompt (printed).
 * In-app: full bilingual content (EN/DE) shown after scanning.
 */
export const SEED_CARDS: MomentCard[] = [
  // ── GROW DATES (1–5) ─────────────────────────────────────────────────────
  {
    id: 'card-01',
    number: 1,
    prompt: 'Find a small plant you both love. Plant it together.',
    type: 'action',
    kind: 'grow-date',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'Grow Something Together',
      titleDe: 'Zusammen etwas zum Wachsen bringen',
      before: 'Find a plant you both actually want to take care of. It doesn\'t have to be big.',
      beforeDe: 'Sucht euch eine Pflanze aus, die ihr gemeinsam pflegen wollt. Sie muss nicht groß sein.',
      tryThis: 'Visit a plant shop or market together. Let each other choose. Buy something small. Plant it together at home. Take a photo today, in three weeks, and in three months.',
      tryThisDe: 'Geht gemeinsam in einen Pflanzenladen oder auf einen Markt. Lasst euch gegenseitig wählen. Kauft etwas Kleines. Pflanzt es zusammen zuhause ein. Macht ein Foto heute, in drei Wochen und in drei Monaten.',
      talkAboutIt: 'What are you planting in your life right now? Where do you feel things are beginning to grow?',
      talkAboutItDe: 'Was pflanzt du gerade in deinem Leben? Wo spürst du, dass etwas anfängt zu wachsen?',
      keepNote: 'What felt alive about this? What surprised you?',
      keepNoteDe: 'Was hat sich lebendig angefühlt? Was hat dich überrascht?',
      comeBack: 'When your plant grows — what do you want to have grown in yourselves?',
      comeBackDe: 'Wenn eure Pflanze wächst — was wollt ihr in euch selbst wachsen lassen?',
    },
  },
  {
    id: 'card-02',
    number: 2,
    prompt: 'Cook something neither of you has ever made. Eat it before it cools.',
    type: 'action',
    kind: 'grow-date',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'Cook Something New',
      titleDe: 'Etwas Neues kochen',
      before: 'Pick something neither of you has ever made. Something that takes a little effort.',
      beforeDe: 'Sucht etwas aus, das keiner von euch je gemacht hat. Etwas, das etwas Mühe braucht.',
      tryThis: 'Cook it together from scratch. Eat it before it cools. No phones at the table.',
      tryThisDe: 'Kocht es gemeinsam von Anfang an. Esst es, bevor es kalt wird. Keine Handys am Tisch.',
      talkAboutIt: 'What\'s something you\'ve always wanted to try but keep putting off? What would it feel like to actually start?',
      talkAboutItDe: 'Was hast du immer mal ausprobieren wollen, aber immer wieder aufgeschoben? Wie wäre es, wirklich anzufangen?',
      keepNote: 'How was it? What will you make next?',
      keepNoteDe: 'Wie war es? Was macht ihr als nächstes?',
      comeBack: 'What\'s the next thing you want to make together?',
      comeBackDe: 'Was wollt ihr als nächstes gemeinsam machen?',
    },
  },
  {
    id: 'card-03',
    number: 3,
    prompt: 'Find a place you haven\'t been together. Spend at least an hour there.',
    type: 'action',
    kind: 'grow-date',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'Go Somewhere New',
      titleDe: 'Irgendwo Neues hingehen',
      before: 'It doesn\'t have to be far. Just somewhere neither of you has been together.',
      beforeDe: 'Es muss nicht weit sein. Einfach irgendwo, wo ihr zusammen noch nie wart.',
      tryThis: 'Find a place you haven\'t been together. Spend at least an hour there. Walk, sit, look around. No agenda.',
      tryThisDe: 'Sucht euch einen Ort aus, an dem ihr noch nie zusammen wart. Bleibt mindestens eine Stunde. Lauft, sitzt, schaut euch um. Kein Plan.',
      talkAboutIt: 'Where is somewhere you\'ve always wanted to go together? What\'s held you back?',
      talkAboutItDe: 'Wo wärt ihr schon immer gern zusammen gewesen? Was hat euch zurückgehalten?',
      keepNote: 'What will you remember about today?',
      keepNoteDe: 'Was werdet ihr von heute in Erinnerung behalten?',
      comeBack: 'Where do you want to go next?',
      comeBackDe: 'Wo wollt ihr als nächstes hin?',
    },
  },
  {
    id: 'card-04',
    number: 4,
    prompt: 'Make something together. It doesn\'t have to be good.',
    type: 'action',
    kind: 'grow-date',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'Make Something Together',
      titleDe: 'Gemeinsam etwas erschaffen',
      before: 'It doesn\'t have to be good. It just has to be made by the two of you.',
      beforeDe: 'Es muss nicht gut sein. Es muss nur von euch beiden gemacht sein.',
      tryThis: 'Make something together — a drawing, a recipe, a playlist, something with your hands. Give it at least 30 minutes. Don\'t quit early.',
      tryThisDe: 'Erschafft gemeinsam etwas — eine Zeichnung, ein Rezept, eine Playlist, etwas mit euren Händen. Lasst euch mindestens 30 Minuten Zeit. Gebt nicht früh auf.',
      talkAboutIt: 'What does it feel like to create something with someone you love? What came up while you were making it?',
      talkAboutItDe: 'Wie fühlt es sich an, mit jemandem, den du liebst, etwas zu erschaffen? Was ist entstanden, während ihr gemacht habt?',
      keepNote: 'Describe what you made. Or just how it felt.',
      keepNoteDe: 'Beschreibt, was ihr gemacht habt. Oder einfach, wie es sich angefühlt hat.',
      comeBack: 'What would you want to make next — if time and skill didn\'t matter?',
      comeBackDe: 'Was würdet ihr als nächstes machen wollen — wenn Zeit und Können keine Rolle spielten?',
    },
  },
  {
    id: 'card-05',
    number: 5,
    prompt: 'Take a walk with no destination. Stop when something catches your attention.',
    type: 'action',
    kind: 'grow-date',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'Walk Without a Destination',
      titleDe: 'Ohne Ziel laufen',
      before: 'Leave your itinerary at home. Let the walk decide itself.',
      beforeDe: 'Lasst den Plan zuhause. Der Weg entscheidet.',
      tryThis: 'Take a walk with no destination. Stop when something catches your attention. Let the other person choose the next turn. Keep going until you\'re both ready to stop.',
      tryThisDe: 'Geht ohne Ziel spazieren. Bleibt stehen, wenn euch etwas auffällt. Lasst den anderen die nächste Abbiegung wählen. Geht weiter, bis ihr beide bereit seid, aufzuhören.',
      talkAboutIt: 'If your relationship had a direction right now — where would it be going? Where do you want it to go?',
      talkAboutItDe: 'Wenn eure Beziehung gerade eine Richtung hätte — wohin würde sie gehen? Wohin wollt ihr, dass sie geht?',
      keepNote: 'Where did you end up? What did you notice along the way?',
      keepNoteDe: 'Wo seid ihr gelandet? Was habt ihr unterwegs bemerkt?',
      comeBack: 'Is there somewhere from today you\'d want to come back to?',
      comeBackDe: 'Gibt es einen Ort von heute, zu dem ihr zurückkehren wollt?',
    },
  },

  // ── SMALL ACTS OF GROWTH (6–10) ──────────────────────────────────────────
  {
    id: 'card-06',
    number: 6,
    prompt: 'Write down one thing you\'ve been putting off. Show it to each other.',
    type: 'action',
    kind: 'small-act',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'One Small Step',
      titleDe: 'Ein kleiner Schritt',
      before: 'Think of something small you\'ve been wanting to do, but keep postponing.',
      beforeDe: 'Denkt an etwas Kleines, das ihr tun wolltet, aber immer wieder aufschiebt.',
      tryThis: 'Write down one thing each of you has been putting off. Not something huge — just one small step. Read it to each other. Then actually do it before your next check-in.',
      tryThisDe: 'Schreibt je eine Sache auf, die ihr aufgeschoben habt. Nichts Riesiges — nur ein kleiner Schritt. Lest es euch vor. Und macht es dann wirklich, bevor ihr euch wieder sprecht.',
      talkAboutIt: 'Why does it feel hard to start? What would it feel like to actually follow through?',
      talkAboutItDe: 'Warum fühlt es sich schwer an anzufangen? Wie würde es sich anfühlen, es wirklich durchzuziehen?',
      keepNote: 'What did you commit to? Come back when you\'ve done it.',
      keepNoteDe: 'Wozu habt ihr euch verpflichtet? Kommt wieder, wenn ihr es gemacht habt.',
      comeBack: 'Did you do it? What happened?',
      comeBackDe: 'Habt ihr es gemacht? Was ist passiert?',
    },
  },
  {
    id: 'card-07',
    number: 7,
    prompt: 'Write one thing you love about this person. Give it to them without explanation.',
    type: 'action',
    kind: 'small-act',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'Write It Down',
      titleDe: 'Aufschreiben',
      before: 'You\'ve been meaning to say this for a while. Today you write it.',
      beforeDe: 'Du hast es schon eine Weile sagen wollen. Heute schreibst du es auf.',
      tryThis: 'Write one thing you love about this person. Not what they do — who they are. Fold the paper and give it to them. No explanation needed.',
      tryThisDe: 'Schreib eine Sache auf, die du an dieser Person liebst. Nicht was sie tut — wer sie ist. Falte das Papier und gib es ihr. Keine Erklärung nötig.',
      talkAboutIt: 'Is it easy or hard for you to say these things out loud? What makes it easier to write them?',
      talkAboutItDe: 'Fällt es dir leicht oder schwer, diese Dinge laut zu sagen? Was macht es leichter, sie aufzuschreiben?',
      keepNote: 'What did you write? How did it feel to give it?',
      keepNoteDe: 'Was hast du geschrieben? Wie hat es sich angefühlt, es zu geben?',
      comeBack: 'Keep the note somewhere you\'ll find it again.',
      comeBackDe: 'Bewahre den Zettel irgendwo auf, wo du ihn wiederfindest.',
    },
  },
  {
    id: 'card-08',
    number: 8,
    prompt: 'Put your phones in another room for two hours. Do something with your hands.',
    type: 'action',
    kind: 'small-act',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'Phones Away',
      titleDe: 'Handys weg',
      before: 'Set a timer. Two hours. Phones go in another room.',
      beforeDe: 'Stellt einen Timer. Zwei Stunden. Handys kommen ins andere Zimmer.',
      tryThis: 'Put your phones in another room for two hours. Do something with your hands — cook, draw, fix something, sit in the garden. Be present without performing it.',
      tryThisDe: 'Legt eure Handys für zwei Stunden ins andere Zimmer. Macht etwas mit euren Händen — kochen, zeichnen, reparieren, im Garten sitzen. Seid präsent, ohne es zu inszenieren.',
      talkAboutIt: 'When do you most wish you had each other\'s full attention? When do you find it hardest to give yours?',
      talkAboutItDe: 'Wann wünschst du dir am meisten die volle Aufmerksamkeit des anderen? Wann fällt es dir selbst am schwersten, sie zu geben?',
      keepNote: 'What did you do? What did you notice?',
      keepNoteDe: 'Was habt ihr gemacht? Was habt ihr bemerkt?',
      comeBack: 'What would it look like to do this more often?',
      comeBackDe: 'Wie würde es aussehen, das öfter zu tun?',
    },
  },
  {
    id: 'card-09',
    number: 9,
    prompt: 'Sit in silence for five minutes. Just be next to each other.',
    type: 'action',
    kind: 'small-act',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'Just Be Here',
      titleDe: 'Einfach da sein',
      before: 'Nothing to achieve. No conversation needed.',
      beforeDe: 'Nichts zu erreichen. Kein Gespräch nötig.',
      tryThis: 'Sit in silence together for five minutes. No phones, no music. Just you and them, side by side. If thoughts come, let them pass. When the timer goes off — stay a little longer if it feels right.',
      tryThisDe: 'Sitzt gemeinsam fünf Minuten in Stille. Keine Handys, keine Musik. Nur ihr zwei, nebeneinander. Wenn Gedanken kommen, lass sie ziehen. Wenn der Timer klingelt — bleibt noch ein bisschen, wenn es sich richtig anfühlt.',
      talkAboutIt: 'When do you feel most at peace together? When is it hardest to just be still?',
      talkAboutItDe: 'Wann fühlt ihr euch zusammen am ruhigsten? Wann fällt es euch am schwersten, einfach still zu sein?',
      keepNote: 'What came up in the silence?',
      keepNoteDe: 'Was ist in der Stille aufgetaucht?',
      comeBack: 'What\'s one thing you want to have more space for?',
      comeBackDe: 'Wofür wollt ihr euch mehr Raum lassen?',
    },
  },
  {
    id: 'card-10',
    number: 10,
    prompt: 'Tell each other what you were afraid of as a child. Listen without fixing.',
    type: 'action',
    kind: 'small-act',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'Tell Each Other',
      titleDe: 'Einander erzählen',
      before: 'This one asks for a little courage. Give each other space to be honest.',
      beforeDe: 'Dieses hier braucht etwas Mut. Gebt einander Raum, ehrlich zu sein.',
      tryThis: 'Tell each other what you were afraid of as a child. Or something you\'ve never said out loud. The other person listens — no fixing, no advice. Then switch.',
      tryThisDe: 'Erzählt einander, wovor ihr als Kind Angst hattet. Oder etwas, das ihr noch nie laut gesagt habt. Der andere hört zu — kein Reparieren, kein Ratschlag. Dann tauscht.',
      talkAboutIt: 'What did it feel like to say that out loud? What did it feel like to be heard?',
      talkAboutItDe: 'Wie hat es sich angefühlt, das laut zu sagen? Wie hat es sich angefühlt, gehört zu werden?',
      keepNote: 'What stayed with you from this conversation?',
      keepNoteDe: 'Was ist von diesem Gespräch bei dir geblieben?',
      comeBack: 'Is there something else you\'ve been holding back?',
      comeBackDe: 'Gibt es noch etwas, das du zurückgehalten hast?',
    },
  },

  // ── GROWING QUESTIONS (11–20) ─────────────────────────────────────────────
  {
    id: 'card-11',
    number: 11,
    prompt: 'Where do you sometimes still feel unseen by me?',
    type: 'question',
    kind: 'growing-question',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'Where do you sometimes feel unseen?',
      titleDe: 'Wo fühlst du dich manchmal noch nicht gesehen?',
      before: 'This one asks for honesty. Give each other space. No explaining, no fixing. Just listen.',
      beforeDe: 'Diese Frage braucht Ehrlichkeit. Gebt einander Raum. Kein Erklären, kein Reparieren. Einfach zuhören.',
      tryThis: 'Take turns answering. Spend at least five minutes each. When one person speaks, the other just listens — no interruptions, no advice. Then switch.',
      tryThisDe: 'Beantwortet abwechselnd. Nehmt euch mindestens fünf Minuten. Wenn eine Person spricht, hört die andere einfach zu. Keine Unterbrechungen, kein Ratschlag. Dann tauscht.',
      talkAboutIt: 'Where do you need more space to be exactly who you are?',
      talkAboutItDe: 'Wo brauchst du mehr Raum, genau du selbst zu sein?',
      keepNote: 'Write what came up, not just what you answered. What did you feel?',
      keepNoteDe: 'Schreibt, was aufgetaucht ist — nicht nur, was ihr geantwortet habt. Was habt ihr gefühlt?',
    },
  },
  {
    id: 'card-12',
    number: 12,
    prompt: 'When do you feel most alive with me?',
    type: 'question',
    kind: 'growing-question',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'When do you feel most alive with me?',
      titleDe: 'Wann fühlst du dich mit mir am lebendigsten?',
      before: 'Close your eyes before you answer. Let the first real memory come.',
      beforeDe: 'Schließ die Augen, bevor du antwortest. Lass die erste echte Erinnerung kommen.',
      tryThis: 'Take turns. Describe a specific moment — not a general feeling. Tell each other about a time when you felt fully alive together. The more specific, the better.',
      tryThisDe: 'Abwechselnd. Beschreibt einen bestimmten Moment — kein allgemeines Gefühl. Erzählt einander von einem Moment, in dem ihr euch wirklich lebendig gefühlt habt. Je konkreter, desto besser.',
      talkAboutIt: 'What makes those moments possible? How could you have more of them?',
      talkAboutItDe: 'Was macht diese Momente möglich? Wie könntet ihr mehr davon haben?',
      keepNote: 'Describe the moment you thought of. Where were you? What made it feel alive?',
      keepNoteDe: 'Beschreibt den Moment, den ihr im Sinn hattet. Wo wart ihr? Was hat ihn lebendig gemacht?',
    },
  },
  {
    id: 'card-13',
    number: 13,
    prompt: 'What helps you open up to me?',
    type: 'question',
    kind: 'growing-question',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'What helps you open up to me?',
      titleDe: 'Was hilft dir, dich mir gegenüber zu öffnen?',
      before: 'This isn\'t about what\'s wrong. It\'s about what makes things easier.',
      beforeDe: 'Hier geht es nicht darum, was falsch ist. Sondern darum, was es leichter macht.',
      tryThis: 'Each person shares two or three things — moments, words, gestures — that make it easier to open up. Be honest. Be kind.',
      tryThisDe: 'Jede Person teilt zwei oder drei Dinge — Momente, Worte, Gesten — die es leichter machen, sich zu öffnen. Ehrlich sein. Freundlich sein.',
      talkAboutIt: 'Is there something the other person does that you want more of?',
      talkAboutItDe: 'Gibt es etwas, das der andere tut, und das du dir öfter wünschst?',
      keepNote: 'What helps you feel safe enough to be honest?',
      keepNoteDe: 'Was hilft dir, dich sicher genug zu fühlen, um ehrlich zu sein?',
    },
  },
  {
    id: 'card-14',
    number: 14,
    prompt: 'What makes our relationship feel warm?',
    type: 'question',
    kind: 'growing-question',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'What makes our relationship feel warm?',
      titleDe: 'Was lässt unsere Beziehung sich warm anfühlen?',
      before: 'Think small. Warmth lives in the tiny things.',
      beforeDe: 'Denkt klein. Wärme lebt in den kleinen Dingen.',
      tryThis: 'Each person names three small things — words, gestures, habits — that make the relationship feel warm. Not grand gestures. The little everyday things.',
      tryThisDe: 'Jede Person nennt drei kleine Dinge — Worte, Gesten, Gewohnheiten — die die Beziehung warm machen. Keine großen Gesten. Die kleinen alltäglichen Dinge.',
      talkAboutIt: 'What\'s one small thing you could do more of?',
      talkAboutItDe: 'Was ist eine kleine Sache, die du öfter tun könntest?',
      keepNote: 'List the small things. The ones that make it feel like home.',
      keepNoteDe: 'Schreibt die kleinen Dinge auf. Die, die es sich wie Zuhause anfühlen lassen.',
    },
  },
  {
    id: 'card-15',
    number: 15,
    prompt: 'Where do you need more light from me?',
    type: 'question',
    kind: 'growing-question',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'Where do you need more light from me?',
      titleDe: 'Wo brauchst du mehr Licht von mir?',
      before: 'This is about what you need — not what\'s missing. Come to it gently.',
      beforeDe: 'Es geht darum, was du brauchst — nicht was fehlt. Geht es sanft an.',
      tryThis: 'Take turns finishing this sentence: "I could use a little more from you when..." Stay open. The goal isn\'t to solve it — it\'s to understand it.',
      tryThisDe: 'Beendet abwechselnd diesen Satz: "Ich könnte ein bisschen mehr von dir gebrauchen, wenn..." Bleibt offen. Das Ziel ist nicht, es zu lösen — sondern es zu verstehen.',
      talkAboutIt: 'What\'s one small thing you could do this week to give that?',
      talkAboutItDe: 'Was ist eine kleine Sache, die du diese Woche tun könntest, um das zu geben?',
      keepNote: 'What did you say you needed? What did you hear the other person need?',
      keepNoteDe: 'Was habt ihr gesagt, dass ihr braucht? Was habt ihr gehört, was der andere braucht?',
    },
  },
  {
    id: 'card-16',
    number: 16,
    prompt: 'When do you feel safe enough to fully bloom?',
    type: 'question',
    kind: 'growing-question',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'When do you feel safe enough to fully bloom?',
      titleDe: 'Wann fühlst du dich sicher genug, um wirklich aufzublühen?',
      before: 'Safety is different for everyone. Let this be about their kind of safe.',
      beforeDe: 'Sicherheit bedeutet für jeden etwas anderes. Lass es um ihre Art von Sicherheit gehen.',
      tryThis: 'Ask each other: when do you feel safe with me? Safe enough to be weird, to be wrong, to be completely yourself? Take your time. Listen fully.',
      tryThisDe: 'Fragt einander: Wann fühlst du dich bei mir sicher? Sicher genug, seltsam zu sein, falsch zu liegen, ganz du selbst zu sein? Nehmt euch Zeit. Hört wirklich zu.',
      talkAboutIt: 'What do you need from the other person to feel that safety more often?',
      talkAboutItDe: 'Was brauchst du vom anderen, um dieses Gefühl von Sicherheit öfter zu haben?',
      keepNote: 'When did you last feel that kind of safe together? Describe the moment.',
      keepNoteDe: 'Wann habt ihr euch zuletzt so sicher gefühlt? Beschreibt den Moment.',
    },
  },
  {
    id: 'card-17',
    number: 17,
    prompt: 'Where do you need space to grow on your own?',
    type: 'question',
    kind: 'growing-question',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'Where do you need space to grow on your own?',
      titleDe: 'Wo brauchst du Raum, um für dich selbst zu wachsen?',
      before: 'This isn\'t about needing distance. It\'s about knowing yourselves well enough to name it.',
      beforeDe: 'Hier geht es nicht darum, Distanz zu brauchen. Sondern darum, sich selbst gut genug zu kennen, um es zu benennen.',
      tryThis: 'Each person describes one area of life where they want to grow on their own — a skill, a habit, an interest. Share it without apology.',
      tryThisDe: 'Jede Person beschreibt einen Lebensbereich, in dem sie für sich selbst wachsen möchte — eine Fähigkeit, eine Gewohnheit, ein Interesse. Teilt es ohne Entschuldigung.',
      talkAboutIt: 'How can you support each other\'s individual growth without getting in the way?',
      talkAboutItDe: 'Wie könnt ihr das individuelle Wachstum des anderen unterstützen, ohne im Weg zu stehen?',
      keepNote: 'What do you want to grow on your own? What support do you need?',
      keepNoteDe: 'Was willst du für dich selbst wachsen lassen? Welche Unterstützung brauchst du dabei?',
    },
  },
  {
    id: 'card-18',
    number: 18,
    prompt: 'What are we still growing into together?',
    type: 'question',
    kind: 'growing-question',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'What are we still growing into together?',
      titleDe: 'Was werden wir noch gemeinsam?',
      before: 'Look forward. Let yourself imagine.',
      beforeDe: 'Schaut nach vorn. Erlaubt euch zu träumen.',
      tryThis: 'Take turns finishing: "I want us to grow into..." It can be something big, something small, something that doesn\'t have words yet. Just let it out.',
      tryThisDe: 'Beendet abwechselnd: "Ich möchte, dass wir noch..." Es kann etwas Großes, etwas Kleines, etwas sein, das noch keine Worte hat. Einfach rauslassen.',
      talkAboutIt: 'What\'s one small step you could take toward that this year?',
      talkAboutItDe: 'Was ist ein kleiner Schritt, den ihr dieses Jahr darauf zu machen könntet?',
      keepNote: 'What did you say you want to grow into? Write it down so you remember.',
      keepNoteDe: 'Was habt ihr gesagt, was ihr noch werden wollt? Schreibt es auf, damit ihr es nicht vergesst.',
      comeBack: 'Come back to this in six months. Has anything changed?',
      comeBackDe: 'Kommt in sechs Monaten hierher zurück. Hat sich etwas verändert?',
    },
  },
  {
    id: 'card-19',
    number: 19,
    prompt: 'How do we find our way back to each other?',
    type: 'question',
    kind: 'growing-question',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'How do we find our way back to each other?',
      titleDe: 'Wie finden wir zueinander zurück?',
      before: 'Every couple has a way back. This is about knowing yours.',
      beforeDe: 'Jedes Paar hat einen Weg zurück. Hier geht es darum, euren zu kennen.',
      tryThis: 'Think about a time you reconnected after feeling distant. What helped? What did the other person do? What did you do? Share it.',
      tryThisDe: 'Denkt an einen Moment, in dem ihr euch wiederverbunden habt, nachdem ihr euch distanziert gefühlt habt. Was hat geholfen? Was hat der andere getan? Was habt ihr getan? Teilt es.',
      talkAboutIt: 'What\'s your signal to the other person that you want to come back?',
      talkAboutItDe: 'Was ist dein Zeichen an den anderen, dass du zurückkommen möchtest?',
      keepNote: 'What did you learn about how you find your way back?',
      keepNoteDe: 'Was habt ihr darüber gelernt, wie ihr zueinander zurückfindet?',
    },
  },
  {
    id: 'card-20',
    number: 20,
    prompt: 'What have we helped each other become?',
    type: 'question',
    kind: 'growing-question',
    edition: 'edition-01',
    status: 'sealed',
    content: {
      title: 'What have we helped each other become?',
      titleDe: 'Wozu haben wir einander verholfen?',
      before: 'This is one to sit with. Don\'t rush it.',
      beforeDe: 'Diese Frage verdient Zeit. Nicht hetzen.',
      tryThis: 'Each person answers: "Because of you, I have become..." Be specific. Think about things you carry differently now — things you see, do, or are — that you learned from them.',
      tryThisDe: 'Jede Person antwortet: "Durch dich bin ich..." Seid konkret. Denkt an Dinge, die ihr jetzt anders tragt — Dinge, die ihr seht, tut, seid — die ihr vom anderen gelernt habt.',
      talkAboutIt: 'What do you want to help each other become next?',
      talkAboutItDe: 'Wozu wollt ihr einander als nächstes verhelfen?',
      keepNote: 'Because of you, I have become... Write it down.',
      keepNoteDe: 'Durch dich bin ich... Schreib es auf.',
    },
  },
];

/** Which cards each space has already preserved a moment for (spaceId → cardIds). */
export const SEED_ACTIVATIONS: Record<string, string[]> = {
  'space-couple-01': ['card-11', 'card-12', 'card-14', 'card-15', 'card-16'],
  'space-friends-01': ['card-05'],
};

/**
 * A deck holds between 15 and 20 cards. Upcoming editions have cardCount 0
 * until their cards are assigned and QR codes generated (done incrementally).
 */
export const DECK_SIZE_RANGE = { min: 15, max: 20 } as const;

/**
 * Couples editions roadmap. Only edition-01 has a finalized deck today
 * (status: available); the rest are on the public roadmap (status: upcoming)
 * with cardCount 0 — their cards aren't assigned yet. Friends editions are
 * intentionally not a product line — friends still use the available
 * couples-neutral editions in a friends space (see PRODUCT.md / decision register).
 */
export const SEED_EDITIONS: Edition[] = [
  {
    id: 'edition-01',
    order: 1,
    name: 'Grow Together',
    subtitle: 'Edition 01 — Sunflower',
    description: 'twenty moments to collect, in any order. choose what feels right.',
    symbol: '🌻',
    color: '#F2B705',
    ink: 'dark',
    status: 'available',
    cardCount: SEED_CARDS.length,
    cards: SEED_CARDS,
  },
  {
    id: 'edition-02',
    order: 2,
    name: 'Love Languages',
    subtitle: 'Edition 02 — Letters',
    description: 'discover how each of you gives and receives love.',
    symbol: '💬',
    color: '#E8A0A0',
    ink: 'dark',
    status: 'upcoming',
    cardCount: 0,
    cards: [],
  },
  {
    id: 'edition-03',
    order: 3,
    name: 'In Presence',
    subtitle: 'Edition 03 — Stillness',
    description: 'phones away, fully here. moments of undivided attention.',
    symbol: '🌿',
    color: '#9CAF88',
    ink: 'dark',
    status: 'upcoming',
    cardCount: 0,
    cards: [],
  },
  {
    id: 'edition-04',
    order: 4,
    name: 'Deep Spice',
    subtitle: 'Edition 04 — Ember',
    description: 'playful heat and honest desire, just for the two of you.',
    symbol: '🌶️',
    color: '#C0392B',
    ink: 'light',
    status: 'upcoming',
    cardCount: 0,
    cards: [],
  },
  {
    id: 'edition-05',
    order: 5,
    name: 'Far Away',
    subtitle: 'Edition 05 — Horizon',
    description: 'for the distance — staying close across the miles.',
    symbol: '✈️',
    color: '#7FA8C9',
    ink: 'dark',
    status: 'upcoming',
    cardCount: 0,
    cards: [],
  },
  {
    id: 'edition-06',
    order: 6,
    name: 'Lovemaxing',
    subtitle: 'Edition 06 — Bloom',
    description: 'small daily acts that compound into closeness.',
    symbol: '✨',
    color: '#F0A070',
    ink: 'dark',
    status: 'upcoming',
    cardCount: 0,
    cards: [],
  },
  {
    id: 'edition-07',
    order: 7,
    name: 'Self Worth',
    subtitle: 'Edition 07 — Mirror',
    description: 'grow as individuals, so you grow as a pair.',
    symbol: '🪞',
    color: '#B8A9C9',
    ink: 'dark',
    status: 'upcoming',
    cardCount: 0,
    cards: [],
  },
  {
    id: 'edition-08',
    order: 8,
    name: 'Wild Cards',
    subtitle: 'Edition 08 — Spark',
    description: 'unexpected dares and spontaneous detours.',
    symbol: '🎲',
    color: '#E8633A',
    ink: 'light',
    status: 'upcoming',
    cardCount: 0,
    cards: [],
  },
  {
    id: 'edition-09',
    order: 9,
    name: 'Hideout',
    subtitle: 'Edition 09 — Nest',
    description: 'slow, cozy moments to retreat into together.',
    symbol: '🏕️',
    color: '#8D7B68',
    ink: 'light',
    status: 'upcoming',
    cardCount: 0,
    cards: [],
  },
  // Life-stage editions — for a specific season of a relationship.
  {
    id: 'edition-10',
    order: 10,
    name: 'Just Started',
    subtitle: 'Edition 10 — Seedling',
    description: 'for the early days — getting to know each other, one moment at a time.',
    symbol: '🌱',
    color: '#A3C9A8',
    ink: 'dark',
    status: 'upcoming',
    cardCount: 0,
    cards: [],
  },
  {
    id: 'edition-11',
    order: 11,
    name: 'After Hours',
    subtitle: 'Edition 11 — Lantern',
    description: 'for busy lives — small moments that fit between everything else.',
    symbol: '🌙',
    color: '#3D4A6B',
    ink: 'light',
    status: 'upcoming',
    cardCount: 0,
    cards: [],
  },
  {
    id: 'edition-12',
    order: 12,
    name: 'After Bedtime',
    subtitle: 'Edition 12 — Hearth',
    description: 'for parents — staying a couple, not just a team.',
    symbol: '🧸',
    color: '#D9A679',
    ink: 'dark',
    status: 'upcoming',
    cardCount: 0,
    cards: [],
  },
];

/** Back-compat: the launch edition. Prefer SEED_EDITIONS / getEdition(id). */
export const SEED_EDITION: Edition = SEED_EDITIONS[0];

export function getEdition(editionId: string): Edition | undefined {
  return SEED_EDITIONS.find((e) => e.id === editionId);
}

export const SEED_MEMORIES: Memory[] = [
  {
    id: 'memory-01',
    cardId: 'card-11',
    spaceId: 'space-couple-01',
    note: 'we talked until 2am about the little things — the way you notice when i go quiet, the way you always make sure i eat. i feel seen in the smallest moments.',
    createdAt: '2026-04-03T21:30:00Z',
    updatedAt: '2026-04-03T21:30:00Z',
  },
  {
    id: 'memory-02',
    cardId: 'card-12',
    spaceId: 'space-couple-01',
    note: 'hiking to the summit. the wind, the silence, the way we just stood there without needing to say anything. that morning felt infinite.',
    createdAt: '2026-04-20T09:15:00Z',
    updatedAt: '2026-04-20T09:15:00Z',
  },
  {
    id: 'memory-03',
    cardId: 'card-14',
    spaceId: 'space-couple-01',
    note: 'you asked me what i needed instead of guessing. that was it. that was all i ever needed.',
    createdAt: '2026-05-10T19:45:00Z',
    updatedAt: '2026-05-10T19:45:00Z',
  },
  {
    id: 'memory-04',
    cardId: 'card-05',
    spaceId: 'space-friends-01',
    note: 'no destination, just walked the river until it got dark. jonas found that tiny bakery. we stayed way too long. easy day, good people.',
    createdAt: '2026-05-24T16:20:00Z',
    updatedAt: '2026-05-24T16:20:00Z',
  },
  {
    id: 'memory-05',
    cardId: 'card-15',
    spaceId: 'space-couple-01',
    note: 'told you where i needed more light. you just listened, then changed something the next day. quietly. that meant everything.',
    createdAt: '2026-06-09T20:10:00Z',
    updatedAt: '2026-06-09T20:10:00Z',
  },
  {
    id: 'memory-06',
    cardId: 'card-16',
    spaceId: 'space-couple-01',
    note: 'sunday morning, nowhere to be. coffee, the window open, your feet on my lap. warm. that\'s the word.',
    createdAt: '2026-06-16T09:30:00Z',
    updatedAt: '2026-06-16T09:30:00Z',
  },
];

export const ONBOARDING_GOALS = [
  { id: 'g1', label: 'deeper conversations', description: 'go beyond day-to-day talk' },
  { id: 'g2', label: 'shared adventures', description: 'discover new places and things together' },
  { id: 'g3', label: 'more presence', description: 'be fully here, phones away' },
  { id: 'g4', label: 'understanding each other', description: 'know what the other person carries' },
  { id: 'g5', label: 'playful moments', description: 'laugh more, create more' },
  { id: 'g6', label: 'quiet closeness', description: 'just being, without doing' },
];
